### ISSUE TITLE
Voice Copy Plugin

### ISSUE THREAD

**Issue by bigsby-exe** [sk89q/HeyVictoria#1]
First off this looks very cool and I will be trying it out as soon as I get home 

2nd is there anyway to use Voice Copy Plugin to record each users voice as a separate audio file as I have been looking for something like that for a long time and did not even think it was possible in TS3

**Comment by sk89q** [comment]
Yes but you'd have to write the part that saves the audio data to audio files, but you don't have to write it in C/C++ if you don't want to because the voice copy plugin sends UDP packets to a local host and port containing the client's ID and the audio data.

The packet format is

```
uint16 clientId;
uchar channelCount;
char[] data;
```

It sends to 127.0.0.1 on port 32000

There's no packet sequence # so it's possible, especially if you were trying to send this across a network, that the packets could be reordered and break things, but you can fix that if you want.

**Comment by bigsby-exe** [comment]
ok cheers would be cool to get something working as there is a lack of this for Team speak but mumble has it natively
